[project]
name = "github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygithub>=2.8.1",
    "python-dotenv>=1.0.1",
    "GitPython>=3.1.43",
    "pyyaml>=6.0.2",
]
